### ISSUE TITLE
Bug in fetching definition containing single quote (')

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/roBOT#1]
![image](https://user-images.githubusercontent.com/55531939/118651301-06987700-b803-11eb-9bf1-19b530de1b25.png)
where the actual output should be this:
![image](https://user-images.githubusercontent.com/55531939/118651587-54ad7a80-b803-11eb-8d34-5141b78b1e57.png)

The error can be fixed by not using split() 

The json where the issue can be found: https://api.dictionaryapi.dev/api/v2/entries/en_US/mountain (or any other definition text containing a single quote)

**Comment by soham4abc** [comment]
I can help to resolve this issue.. will you pls assign?

**Comment by danger-ahead** [comment]
issue resolved!

**Comment by danger-ahead** [comment]
## not yet fixed
you can open any other dictionary api if you want. just make sure its completely open source :)
