### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/roBOT#10]
#### NOTE:
For fixing the issue, **head over to the tutorial** and **write up all the necessary steps in the README**. Mention the creation of the **.env** file and naming the tokens. Also mention about generating the **discord application token** and **rapidAPI token**.

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by soham4abc** [comment]
> Can you assign this issue to me?

You are assigned go ahead!!

**Comment by soham4abc** [comment]
@aditya28sarin  If you like you can any kind of modificatio to make the `README` more approachable! Feel free!
