### ISSUE TITLE
🚀 Feature: An Error handler

### ISSUE THREAD

**Issue by bartick** [danger-ahead/roBOT#118]
### 🔖 Feature description

This will be a event who will be responsible for handling most of the API errors that discord throws during a API request.

Or it can remove unwanted errors. Like parsing error.

### 🎤 Pitch

This will not be a visual feature but will help the bot understand what kind of error has happened and can reply with a specific message without handling the same error for every command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by bartick** [comment]
I would like this to be assigned to me.
I would like to know which folder should I add the event to and should I create a new cog or there is an existing cog where I can add it to.

Should I do the PR in master/development ??

**Comment by eitozx** [comment]
> I would like this to be assigned to me. I would like to know which folder should I add the event to and should I create a new cog or there is an existing cog where I can add it to.
> 
> Should I do the PR in master/development ??

Yes & do it in master branch. Cuz we merged development to master just like yesterday.

**Comment by danger-ahead** [comment]
> I would like this to be assigned to me. I would like to know which folder should I add the event to and should I create a new cog or there is an existing cog where I can add it to.
> 
> Should I do the PR in master/development ??

Seems like an excellent proposition.
There's no existing cog. You need to create a new one.
And you can perhaps do it in the `database` folder. Though we need to change the name of this directory now. Can be renamed to something like `admin`.
