### ISSUE TITLE
Delete file contents of `SCREENSHOTS.md`

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/roBOT#39]
`SCREENSHOTS.md ` located in `docs` contains the links to screenshots.
**Delete** the contents of `SCREENSHOTS.md` such that it becomes a **blank file**.

**Comment by RiddhiAthreya** [comment]
@danger-ahead can I work on this issue?

**Comment by danger-ahead** [comment]
@RiddhiAthreya go ahead!
