### ISSUE TITLE
Code needs housekeeping and refactoring.

### ISSUE THREAD

**Issue by OBITORASU** [danger-ahead/roBOT#50]
## Description
Currently `main.py` is riddled with various commands and their implementation. The code also seem to be very repetitive with a lot of recurring `if else` statements. I think a better approach would be to move all the commands and their respective implementations to lets say a structured directory like `roBOT/core/commands/` and subsequently import the commands and their functionalities in the `main.py` file. Overall this would make it a lot easier for contributors as well as maintainers to keep track of all the current commands and potentially the newer ones which have been planned for the future.

**Comment by danger-ahead** [comment]
much needed!
