### ISSUE TITLE
Replace `if-elif` blocks

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/roBOT#66]
#### In [`commands/help.py`](https://github.com/danger-ahead/roBOT/blob/master/commands/help.py), there are too many `if-elif` conditional blocks. The same thing can be implemented by using `dict`. This, on the whole, would increase code-readability and make it easier for the maintainers to keep track of the code.

For more information on this implementation, kindly refer to [`main.py`](https://github.com/danger-ahead/roBOT/blob/master/main.py).
Other important resources needed for this approach are `exec()` and `eval()`.

**Comment by kriptonian1** [comment]
Okey I will work on this tomorrow

**Comment by kriptonian1** [comment]
@danger-ahead fixed this issue in #72 pls check and merge
