### ISSUE TITLE
Lines indicating successful execution are missing

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/roBOT#70]
#### You need to add two lines to make this happen. The lines to be added are provided in the following section.

The updated structure will be as follows:

```
elif message.content.startswith("$"):

    if message.author.guild_permissions.administrator:
        if:
            <all the lines originally under the `if` block go here>
            await message.add_reaction("\U0001f44d") #new line to be added under if
        else:
            <all the lines originally under `else` the block go here>
            await message.add_reaction("\U0001f44E") #new line to be added under else
```

**Comment by Edald123** [comment]
Hi!, may I work on this issue?

**Comment by danger-ahead** [comment]
@Edald123 Go Ahead! I'm assigning you.

> Hi!, may I work on this issue?

**Comment by Edald123** [comment]
Great thanks! I will be sharing my work.

**Comment by Edald123** [comment]
Hi, I already added the 2 lines requested correctly, I can create the PR now but before, I would like to know if I need to create or execute any tests or add any special comments. Thank you!

**Comment by soham4abc** [comment]
> Hi, If I understood correctly it was only necessary to add the specified lines of code, so I already added the 2 lines requested correctly, I can create the PR now but before, I would like to know if I need to create or execute any tests or add any special comments since when I tried to create the PR it asked me some of this information. Thank you!

No need to create any tests! You can make the PR. If any changes are required, we will let you know!

**Comment by Edald123** [comment]
I already made the requested changes, let me know if anything else needs to be done!
