### ISSUE TITLE
Add an Issue Template

### ISSUE THREAD

**Issue by soham4abc** [danger-ahead/roBOT#78]
Would like to see a well documented Issue template here.
Go through the project and make a tailored Issue template

**Comment by vivekkj123** [comment]
Assign this issue to me. I will work on This issue..

Thanks

**Comment by belelaritra** [comment]
I would like to work on this issue.

**Comment by soham4abc** [comment]
> Assign this issue to me. I will work on This issue..
> 
> Thanks

It's all yours. Feel free to work on it!
