### ISSUE TITLE
Revamp the `_hi` command

### ISSUE THREAD

**Issue by soham4abc** [danger-ahead/roBOT#79]
Would like to see a better response from the bot when using the `_hi` command. Customize it your way keeping in line with the nature of the bot.

A Screenshot of the new response is **Mandatory** in PR

file to be edited:
`roBOT/commands/hi_contrib.py`

**Comment by smart-worker** [comment]
I would like to work on this. Can you assign me sir?

**Comment by soham4abc** [comment]
> I would like to work on this. Can you assign me sir?

It's all yours. Feel free to work on it!

**Comment by smart-worker** [comment]
Thanks a lot.

**Comment by soham4abc** [comment]
#81 Closes this
