### ISSUE TITLE
errors in song search feature

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/roBOT#8]
1. Error in line 150 (the key should be `url`).
2. Line 151 is redundant. Should be removed.
3. Error in line 144 (there's no `txt` attribute, it should be changed to `text`).
4. Provide a new line between lines 132 and 133 (to increase code readability).
5. Lines 149 and 150 can be merged together with a `\n` like in line 130.
6. Line 149's text can be changed to something like `"Most famous song: "`.
7. Line 150's text can be changed to `"Lyrics can be found at: "`.

**Comment by infuman69** [comment]
I will fix it.My bad

**Comment by danger-ahead** [comment]
fixed @infuman69 😄
