### ISSUE TITLE
Add the Commands in webpage

### ISSUE THREAD

**Issue by soham4abc** [danger-ahead/roBOT#84]
Add all the commands in the Webpage.
Screenshot should be provided reflecting the changes!

File to be changed : `roBOT/pages/command.html`

All commands can be found here: https://github.com/danger-ahead/roBOT/blob/master/docs/COMMANDS.md

**Comment by alceil** [comment]
I can do this can you assign this to me

**Comment by soham4abc** [comment]
Go ahead feel free to work! @alceil

**Comment by alceil** [comment]
Thanks @soham4abc

**Comment by adityash1** [comment]
> 
> 
> Add all the commands in the Webpage. Screenshot should be provided reflecting the changes!
> 
> File to be changed : `roBOT/pages/command.html`
> 
> All commands can be found here: https://github.com/danger-ahead/roBOT/blob/master/docs/COMMANDS.md

is this issue still open? may i work on this?

**Comment by danger-ahead** [comment]
@alceil if you're unable to work on it, do let us know.

**Comment by adityash1** [comment]
@danger-ahead can i take this issue?

**Comment by danger-ahead** [comment]
> @danger-ahead can i take this issue?
Go Ahead @adityash1

**Comment by adityash1** [comment]
Its my first time. Thanks!

> 
> 
> > @danger-ahead can i take this issue?
> > Go Ahead @adityash1
